FROM bitnami/spark:3.5

USER root

RUN install_packages python3-pip

COPY requirements.txt /tmp/requirements.txt
RUN python3 -m pip install --no-cache-dir -r /tmp/requirements.txt

WORKDIR /workspace
